# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"validate_type": "00_core.ipynb",
         "validate": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://MaxGunton.github.io/mval/"

git_url = "https://github.com/MaxGunton/mval/tree/main/"

def custom_doc_links(name): return None
